
user:
  mrzhu:
    server_path: /home/mrzhu/data/
    dataset_path: /home/mrzhu/data/CRC-HE/
    dataset_path_gan: /home/mrzhu/data/CRC-HE-GAN/
    checkpoint_path: /home/mrzhu/data/classification
  student:
    server_path: /home/student/mrzhu/data/
    # server_path: /home/student/data/
    # 训练和验证文件夹，该文件夹下有train和val文件夹
    dataset_path: /home/student/mrzhu/data/CRC-HE/
    dataset_path_gan: /home/student/mrzhu/data/CRC-HE-GAN/

  root:
    server_path: /root/autodl-tmp/data/
    dataset_path: /root/autodl-tmp/data/CRC-HE/
    dataset_path_gan: /root/autodl-tmp/data/CRC-HE-GAN/
    checkpoint_path: /root/autodl-tmp/data/classification